---
name: Deploy Synapse ID Generator (Code pipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      VPC_SUBNET_COLOR:
        required: true
        type: string
        description: VPC subnet color
      IDGEN_HOSTED_ZONE_ID:
        required: true
        type: string
        description: ID generator hosted zone ID

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS="CommandToExecute=\"scripts/build_synapse_etl_jobs.sh ${{ inputs.STACK }} ${{ inputs.VPC_SUBNET_COLOR }} ${{ inputs.IDGEN_HOSTED_ZONE_ID }} \""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      SECOND_REPO_NAME: Synapse-Stack-Builder
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
