---
name: Deploy Synapse CDN (CodePipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      SUBDOMAIN:
        required: true
        type: string
        description: www or staging or tst
      CERTIFICATE_ARN:
        required: true
        type: string
        description: The ARN of the certificate used on the distribution

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS="CommandToExecute=\"scripts/build_synapse_cdn.sh ${{ inputs.STACK }} ${{ inputs.SUBDOMAIN }} ${{ inputs.CERTIFICATE_ARN }} \""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      SECOND_REPO_NAME: Synapse-Stack-Builder
      # TODO omit the following two lines
      SECOND_REPO_OWNER: brucehoff
      SECOND_REPO_BRANCH: PLFM-9253
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
