---
name: Build Synapse Stack (CodePipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: staging or prod
      INSTANCE:
        required: true
        type: string
        description: example, 544
      REPO_AND_WORKERS_VERSION:
        required: true
        type: string
      REPO_BEANSTALK_VERSION:
        required: true
        type: number
        description: example, 0
      PORTAL_VERSION:
        required: true
        type: string
        description: example, 544.0-4-gd18c3167f2
      PORTAL_BEANSTALK_VERSION:
        required: true
        type: number
        description: example, 0
      VPC_SUBNET_COLOR:
        required: true
        type: string
        description: Red, Green, or Blue
      BEANSTALK_PLATFORM_VERSION:
        required: true
        type: string
        description: example, 5.5.0
        default: 5.5.0

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS="CommandToExecute=\"scripts/build_synapse_stack.sh ${{ inputs.STACK }} ${{ inputs.INSTANCE }} ${{ inputs.REPO_AND_WORKERS_VERSION }} ${{ inputs.REPO_BEANSTALK_VERSION }} ${{ inputs.PORTAL_VERSION }} ${{ inputs.PORTAL_BEANSTALK_VERSION }} ${{ inputs.VPC_SUBNET_COLOR }} ${{ inputs.BEANSTALK_PLATFORM_VERSION }} \""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      USE_STACK_BUILDER: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
