---
name: Migration, Prod to Staging (CodePipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      REMAIN_READ_ONLY_MODE:
        required: true
        type: boolean
      SERVICE_KEY:
        required: true
        type: string

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        # Note: Migration-Utility is incompatible with Java in amazonlinux-x86_64-standard:5.0
        # so we use amazonlinux-x86_64-standard:corretto11 instead.
        run: |
          PIPELINE_PARAMETERS="BuildImage=\"aws/codebuild/amazonlinux-x86_64-standard:corretto11\",CommandToExecute=\"scripts/migration_prod_staging.sh ${{ inputs.STACK }} ${{ inputs.REMAIN_READ_ONLY_MODE }} ${{ inputs.SERVICE_KEY }}\""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      SECOND_REPO_NAME: Synapse-Migration-Utility
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
