---
name: Update feature status

on:
  workflow_call:
    inputs:
      FEATURE_STATUS:
        required: false
        type: boolean
        default: true
        description: true to enable feature or false to disable
      FEATURE:
        required: true
        type: string
        description:  The feature to enable or disable
      STACK:
        required: true
        type: string
        description: Stack to affect

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS=\
          "CommandToExecute=\"scripts/update_feature_status.sh ${{ inputs.FEATURE_STATUS }} ${{ inputs.FEATURE }} ${{ inputs.STACK }}\""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
