---
name: Delete Realm

on:
  workflow_call:
    inputs:
      ID:
        required: true
        type: string
        description: ID of the realm to delete

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS=\
          "CommandToExecute=\"scripts/delete_realm.sh ${{ inputs.ID }} ${{ vars.SYNAPSE_HOST }}\""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
