---
name: Deploy Synapse Network Load Balancers (Code pipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      NLB_RECORDS_CSV:
        required: true
        type: string
        description: NLB records CSV
      AZ_PER_NLB:
        required: true
        type: string
        description: Availability zones per NLB

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS="CommandToExecute=\"scripts/build_synapse_nlb.sh ${{ inputs.STACK }} ${{ inputs.NLB_RECORDS_CSV }} ${{ inputs.AZ_PER_NLB }} \""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      SECOND_REPO_NAME: Synapse-Stack-Builder
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
